/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAdivinanza;

/**
 *
 * @author ROY2404
 */
public class AdminMODE extends javax.swing.JFrame {

    /**
     * Creates new form AdminMODE
     */
    public AdminMODE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabelTituloAdminMODE = new javax.swing.JLabel();
        jLabelOpcion1 = new javax.swing.JLabel();
        jLabelOpcion2 = new javax.swing.JLabel();
        jLabelOpcion3 = new javax.swing.JLabel();
        jLabelOpcion4 = new javax.swing.JLabel();
        jLabelOpcion5 = new javax.swing.JLabel();
        jLabelOpcion6 = new javax.swing.JLabel();
        labelIngreseOpcionAdminMODE = new java.awt.Label();
        textFieldColocarOpcionAdminMode = new java.awt.TextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloAdminMODE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTituloAdminMODE.setText("Modo Administrador");

        jLabelOpcion1.setText("1. Mostrar preguntas y respuestas");

        jLabelOpcion2.setText("2. Modificar pregunta y respuesta");

        jLabelOpcion3.setText("3. Agregar preguntas y respuestas");

        jLabelOpcion4.setText("4. Eliminar pregunta y respuesta");

        jLabelOpcion5.setText("5. Jugar");

        jLabelOpcion6.setText("6. Salir");

        labelIngreseOpcionAdminMODE.setText("Ingrese Opcion");

        textFieldColocarOpcionAdminMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldColocarOpcionAdminModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(labelIngreseOpcionAdminMODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(textFieldColocarOpcionAdminMode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOpcion2)
                            .addComponent(jLabelOpcion3)
                            .addComponent(jLabelOpcion1)
                            .addComponent(jLabelOpcion4)
                            .addComponent(jLabelOpcion5)
                            .addComponent(jLabelOpcion6))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTituloAdminMODE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloAdminMODE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOpcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOpcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOpcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOpcion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOpcion5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOpcion6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIngreseOpcionAdminMODE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldColocarOpcionAdminMode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldColocarOpcionAdminModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldColocarOpcionAdminModeActionPerformed

        String inputText = textFieldColocarOpcionAdminMode.getText();
        try {
            int opcion = Integer.parseInt(inputText);
            switch (opcion) {
                case 1:
                    MostrarPreguntasRespuestas MostrarPreguntasRespuestas = new MostrarPreguntasRespuestas();
                    MostrarPreguntasRespuestas.setVisible(true);
                    this.dispose();
                    break;
                case 2:
                    ModificarPreguntasRespuestas ModificarPreguntasRespuestas = new ModificarPreguntasRespuestas();
                    ModificarPreguntasRespuestas.setVisible(true);
                    this.dispose();
                    break;
                case 3:
                    AgregarPreguntasRespuestas AgregarPreguntasRespuestas = new AgregarPreguntasRespuestas();
                    AgregarPreguntasRespuestas.setVisible(true);
                    this.dispose();
                    break;
                case 4:
                    EliminarPregunta EliminarPregunta = new EliminarPregunta();
                    EliminarPregunta.setVisible(true);
                    this.dispose();
                    break;
                case 5:
                    CantidadPreguntasAdmin CantidadPreguntasAdmin = new CantidadPreguntasAdmin();
                    CantidadPreguntasAdmin.setVisible(true);
                    this.dispose();
                    break;
                case 6:
                    LOGINMODE LOGINMODE = new LOGINMODE();
                    LOGINMODE.setVisible(true);
                    this.dispose();
                    break;
             
            }
        } catch (NumberFormatException ex) {
            
        }
        
    }//GEN-LAST:event_textFieldColocarOpcionAdminModeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMODE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelOpcion1;
    private javax.swing.JLabel jLabelOpcion2;
    private javax.swing.JLabel jLabelOpcion3;
    private javax.swing.JLabel jLabelOpcion4;
    private javax.swing.JLabel jLabelOpcion5;
    private javax.swing.JLabel jLabelOpcion6;
    private javax.swing.JLabel jLabelTituloAdminMODE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label labelIngreseOpcionAdminMODE;
    private java.awt.TextField textFieldColocarOpcionAdminMode;
    // End of variables declaration//GEN-END:variables
}
