/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAdivinanza;

/**
 *
 * @author ROY2404
 */
public class AgregarPreguntasRespuestas extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPreguntasRespuestas
     */
    public AgregarPreguntasRespuestas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelAgregarPreguntasRespuestas = new javax.swing.JLabel();
        jLabelMensajeParaAgregarPreguntas = new javax.swing.JLabel();
        jLabelIngresaPreguntaAgregar = new javax.swing.JLabel();
        jLabelIngresaRespuestaAgregar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneColocarPreguntaAgregar = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneColocarRespuestaAgregar = new javax.swing.JTextPane();
        jButtonAgregarPreguntasRespuestas = new javax.swing.JButton();

        jLabel2.setText("Ingrese el índice de la pregunta que desea modificar:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAgregarPreguntasRespuestas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelAgregarPreguntasRespuestas.setText("Agregar Preguntas y Respuestas");

        jLabelMensajeParaAgregarPreguntas.setText("Ingrese las preguntas a agregar, separadas por un salto de línea. Escriba 'fin' para terminar:");

        jLabelIngresaPreguntaAgregar.setText("Pregunta:");

        jLabelIngresaRespuestaAgregar.setText("Respuesta:");

        jScrollPane1.setViewportView(jTextPaneColocarPreguntaAgregar);

        jScrollPane2.setViewportView(jTextPaneColocarRespuestaAgregar);

        jButtonAgregarPreguntasRespuestas.setText("Agregar");
        jButtonAgregarPreguntasRespuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarPreguntasRespuestasMouseClicked(evt);
            }
        });
        jButtonAgregarPreguntasRespuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntasRespuestasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensajeParaAgregarPreguntas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIngresaRespuestaAgregar)
                                    .addComponent(jLabelIngresaPreguntaAgregar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabelAgregarPreguntasRespuestas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jButtonAgregarPreguntasRespuestas)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAgregarPreguntasRespuestas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMensajeParaAgregarPreguntas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelIngresaPreguntaAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIngresaRespuestaAgregar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregarPreguntasRespuestas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarPreguntasRespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntasRespuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPreguntasRespuestasActionPerformed

    private void jButtonAgregarPreguntasRespuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntasRespuestasMouseClicked
        AdminMODE ventanaAdminMODE = new AdminMODE();
        ventanaAdminMODE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAgregarPreguntasRespuestasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPreguntasRespuestas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarPreguntasRespuestas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAgregarPreguntasRespuestas;
    private javax.swing.JLabel jLabelIngresaPreguntaAgregar;
    private javax.swing.JLabel jLabelIngresaRespuestaAgregar;
    private javax.swing.JLabel jLabelMensajeParaAgregarPreguntas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPaneColocarPreguntaAgregar;
    private javax.swing.JTextPane jTextPaneColocarRespuestaAgregar;
    // End of variables declaration//GEN-END:variables
}
