/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAdivinanza;

/**
 *
 * @author ROY2404
 */
public class CantidadPreguntasAdmin extends javax.swing.JFrame {

    /**
     * Creates new form CantidadPreguntasAdmin
     */
    public CantidadPreguntasAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIngreseCantidadPreguntasAdmin = new javax.swing.JLabel();
        jTextFieldColocarCantidadPreguntasAdmin = new javax.swing.JTextField();
        jButtonjugarAdminMode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIngreseCantidadPreguntasAdmin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelIngreseCantidadPreguntasAdmin.setText("INGRESE LA CANTIDAD DE PREGUNTAS");

        jTextFieldColocarCantidadPreguntasAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColocarCantidadPreguntasAdminActionPerformed(evt);
            }
        });

        jButtonjugarAdminMode.setText("JUGAR");
        jButtonjugarAdminMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonjugarAdminModeMouseClicked(evt);
            }
        });
        jButtonjugarAdminMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjugarAdminModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelIngreseCantidadPreguntasAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldColocarCantidadPreguntasAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonjugarAdminMode)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIngreseCantidadPreguntasAdmin)
                    .addComponent(jTextFieldColocarCantidadPreguntasAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonjugarAdminMode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonjugarAdminModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjugarAdminModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonjugarAdminModeActionPerformed

    private void jTextFieldColocarCantidadPreguntasAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColocarCantidadPreguntasAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColocarCantidadPreguntasAdminActionPerformed

    private void jButtonjugarAdminModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonjugarAdminModeMouseClicked
        intJuego intJuego = new intJuego();
        intJuego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonjugarAdminModeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CantidadPreguntasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CantidadPreguntasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CantidadPreguntasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CantidadPreguntasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CantidadPreguntasAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonjugarAdminMode;
    private javax.swing.JLabel jLabelIngreseCantidadPreguntasAdmin;
    private javax.swing.JTextField jTextFieldColocarCantidadPreguntasAdmin;
    // End of variables declaration//GEN-END:variables
}
