/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAdivinanza;

/**
 *
 * @author ROY2404
 */
public class intJuego extends javax.swing.JFrame {

    /**
     * Creates new form interfazAdivinanza1
     */
    public intJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTemaElegido = new java.awt.Label();
        labelInstrucciones = new java.awt.Label();
        labelLasInstrucciones = new java.awt.Label();
        labelBuenaSuerte = new java.awt.Label();
        labelTema = new java.awt.Label();
        jLabelJugador = new javax.swing.JLabel();
        java.awt.Label labelNombreJugador = new java.awt.Label();
        labelAdivinanzaTitulo = new java.awt.Label();
        labelPregunta = new java.awt.Label();
        labelNumPregunta = new java.awt.Label();
        cuadroDeAdivinanza = new java.awt.Label();
        jLabelaImagen1 = new javax.swing.JLabel();
        jLabelaImagen2 = new javax.swing.JLabel();
        jLabelaImagen3 = new javax.swing.JLabel();
        jLabelaImagen4 = new javax.swing.JLabel();
        jLabelaImagen6 = new javax.swing.JLabel();
        jLabelaImagen5 = new javax.swing.JLabel();
        jLabelaImagen7 = new javax.swing.JLabel();
        jLabelaImagen8 = new javax.swing.JLabel();
        jLabelaImagen9 = new javax.swing.JLabel();
        jLabelaImagen10 = new javax.swing.JLabel();
        labelTiempo = new java.awt.Label();
        jLabelTiempoCorre = new javax.swing.JLabel();
        javax.swing.JLabel jLabelGifPensativo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADIIVINATE ESTA");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1800, 800));
        setMinimumSize(new java.awt.Dimension(1800, 800));
        setPreferredSize(new java.awt.Dimension(1800, 840));
        setResizable(false);

        labelTemaElegido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTemaElegido.setText("ANIMALES");

        labelInstrucciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelInstrucciones.setText("INSTRUCCIONES:");

        labelLasInstrucciones.setText("Lee la adivinanza y luego has click en la imagen correcta.");

        labelBuenaSuerte.setText("¡¡BUENA SUERTE!!");

        labelTema.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTema.setText("TEMA :");

        jLabelJugador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelJugador.setText("JUGADOR :");

        labelNombreJugador.setText("Nombre de jugador");

        labelAdivinanzaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelAdivinanzaTitulo.setText("ADIVINANZA");

        labelPregunta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelPregunta.setText("PREGUNTA: ");

        labelNumPregunta.setText("1");

        cuadroDeAdivinanza.setBackground(new java.awt.Color(240, 245, 246));
        cuadroDeAdivinanza.setFont(new java.awt.Font("Arial", 0, 27)); // NOI18N

        jLabelaImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abeja.png"))); // NOI18N
        jLabelaImagen1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen1MouseClicked(evt);
            }
        });

        jLabelaImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camaleon.png"))); // NOI18N
        jLabelaImagen2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen2MouseClicked(evt);
            }
        });

        jLabelaImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cangrejo.png"))); // NOI18N
        jLabelaImagen3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen3MouseClicked(evt);
            }
        });

        jLabelaImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caracol.png"))); // NOI18N
        jLabelaImagen4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen4MouseClicked(evt);
            }
        });

        jLabelaImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/luciernaga.png"))); // NOI18N
        jLabelaImagen6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen6MouseClicked(evt);
            }
        });

        jLabelaImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estrella.png"))); // NOI18N
        jLabelaImagen5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen5MouseClicked(evt);
            }
        });

        jLabelaImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mariposa.png"))); // NOI18N
        jLabelaImagen7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen7MouseClicked(evt);
            }
        });

        jLabelaImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/murcielago.png"))); // NOI18N
        jLabelaImagen8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen8MouseClicked(evt);
            }
        });

        jLabelaImagen9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rana.png"))); // NOI18N
        jLabelaImagen9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen9MouseClicked(evt);
            }
        });

        jLabelaImagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/raton.png"))); // NOI18N
        jLabelaImagen10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jLabelaImagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelaImagen10MouseClicked(evt);
            }
        });

        labelTiempo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTiempo.setText("TIEMPO :");

        jLabelTiempoCorre.setText("Tiempo corriendo");

        jLabelGifPensativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pensar.gif"))); // NOI18N
        jLabelGifPensativo.setText("jLabel5");
        jLabelGifPensativo.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTemaElegido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelaImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelaImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelJugador)
                                .addGap(16, 16, 16)
                                .addComponent(labelNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNumPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTiempoCorre)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelLasInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelAdivinanzaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(276, 276, 276)
                                        .addComponent(labelBuenaSuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabelGifPensativo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelaImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelaImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelaImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelaImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelaImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelaImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cuadroDeAdivinanza, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelaImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelaImagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelTemaElegido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLasInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelJugador))
                            .addComponent(labelNombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTiempoCorre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAdivinanzaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBuenaSuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuadroDeAdivinanza, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelGifPensativo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelaImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelaImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelaImagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelaImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelaImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelaImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelaImagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabelaImagen9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelaImagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelaImagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        labelTemaElegido.getAccessibleContext().setAccessibleName("labelTemaElegido");
        labelInstrucciones.getAccessibleContext().setAccessibleName("labelInstrucciones");
        labelLasInstrucciones.getAccessibleContext().setAccessibleName("labelLasInstrucciones");
        labelBuenaSuerte.getAccessibleContext().setAccessibleName("labelBuenaSuerte");
        labelTema.getAccessibleContext().setAccessibleName("labelTema");
        jLabelJugador.getAccessibleContext().setAccessibleName("jLabelJugador");
        labelNombreJugador.getAccessibleContext().setAccessibleName("labelNombreJugador");
        labelAdivinanzaTitulo.getAccessibleContext().setAccessibleName("labelAdivinanzaTitulo");
        labelPregunta.getAccessibleContext().setAccessibleName("labelPregunta");
        labelNumPregunta.getAccessibleContext().setAccessibleName("labelNumPregunta");
        cuadroDeAdivinanza.getAccessibleContext().setAccessibleName("cuadroDeAdivinanza");
        jLabelaImagen1.getAccessibleContext().setAccessibleName("jLabelaImagen1");
        jLabelaImagen2.getAccessibleContext().setAccessibleName("jLabelaImagen2");
        jLabelaImagen3.getAccessibleContext().setAccessibleName("jLabelaImagen3");
        jLabelaImagen4.getAccessibleContext().setAccessibleName("jLabelaImagen4");
        jLabelaImagen6.getAccessibleContext().setAccessibleName("jLabelaImagen6");
        jLabelaImagen5.getAccessibleContext().setAccessibleName("jLabelaImagen5");
        jLabelaImagen7.getAccessibleContext().setAccessibleName("jLabelaImagen7");
        jLabelaImagen8.getAccessibleContext().setAccessibleName("jLabelaImagen8");
        jLabelaImagen9.getAccessibleContext().setAccessibleName("jLabelaImagen9");
        jLabelaImagen10.getAccessibleContext().setAccessibleName("jLabelaImagen10");
        labelTiempo.getAccessibleContext().setAccessibleName("labelTiempo");
        jLabelTiempoCorre.getAccessibleContext().setAccessibleName("jLabelTiempoCorre");
        jLabelGifPensativo.getAccessibleContext().setAccessibleName("jLabelGifPensativo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelaImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen1MouseClicked

    private void jLabelaImagen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen2MouseClicked

    private void jLabelaImagen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen3MouseClicked

    private void jLabelaImagen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen4MouseClicked

    private void jLabelaImagen5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen5MouseClicked

    private void jLabelaImagen6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen6MouseClicked

    private void jLabelaImagen7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen7MouseClicked

    private void jLabelaImagen8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen8MouseClicked

    private void jLabelaImagen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen9MouseClicked

    private void jLabelaImagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelaImagen10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelaImagen10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label cuadroDeAdivinanza;
    private javax.swing.JLabel jLabelJugador;
    private javax.swing.JLabel jLabelTiempoCorre;
    private javax.swing.JLabel jLabelaImagen1;
    private javax.swing.JLabel jLabelaImagen10;
    private javax.swing.JLabel jLabelaImagen2;
    private javax.swing.JLabel jLabelaImagen3;
    private javax.swing.JLabel jLabelaImagen4;
    private javax.swing.JLabel jLabelaImagen5;
    private javax.swing.JLabel jLabelaImagen6;
    private javax.swing.JLabel jLabelaImagen7;
    private javax.swing.JLabel jLabelaImagen8;
    private javax.swing.JLabel jLabelaImagen9;
    private java.awt.Label labelAdivinanzaTitulo;
    private java.awt.Label labelBuenaSuerte;
    private java.awt.Label labelInstrucciones;
    private java.awt.Label labelLasInstrucciones;
    private java.awt.Label labelNumPregunta;
    private java.awt.Label labelPregunta;
    private java.awt.Label labelTema;
    private java.awt.Label labelTemaElegido;
    private java.awt.Label labelTiempo;
    // End of variables declaration//GEN-END:variables
}
