/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAdivinanza;

/**
 *
 * @author ROY2404
 */
public class LOGINMODE extends javax.swing.JFrame {

    /**
     * Creates new form usuarioycontraseña
     */
    public LOGINMODE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabelComoDeseaIngresar = new javax.swing.JLabel();
        jButtonBotonIngresarComoAdminUsuario = new javax.swing.JButton();
        jTextFieldColocaELModo = new javax.swing.JTextField();
        jLabelEscribeModo = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelComoDeseaIngresar.setText("¿DESEA INGRESAR COMO administrador o usuario?");

        jButtonBotonIngresarComoAdminUsuario.setText("INGRESAR");
        jButtonBotonIngresarComoAdminUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBotonIngresarComoAdminUsuarioMouseClicked(evt);
            }
        });
        jButtonBotonIngresarComoAdminUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBotonIngresarComoAdminUsuarioActionPerformed(evt);
            }
        });

        jTextFieldColocaELModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColocaELModoActionPerformed(evt);
            }
        });

        jLabelEscribeModo.setText("Escribe el Modo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelComoDeseaIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabelEscribeModo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldColocaELModo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBotonIngresarComoAdminUsuario)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelComoDeseaIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColocaELModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEscribeModo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBotonIngresarComoAdminUsuario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBotonIngresarComoAdminUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBotonIngresarComoAdminUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBotonIngresarComoAdminUsuarioActionPerformed

    private void jTextFieldColocaELModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColocaELModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColocaELModoActionPerformed

    private void jButtonBotonIngresarComoAdminUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBotonIngresarComoAdminUsuarioMouseClicked
         String inputText = jTextFieldColocaELModo.getText();
        // Aquí se verifica el valor ingresado y se llama a los métodos correspondientes
        if ("usuario".equals(inputText)) {
            UsuarioEmpezarJuego UsuarioEmpezarJuego = new UsuarioEmpezarJuego();
            UsuarioEmpezarJuego.setVisible(true);
        this.dispose();;
        } else {
            AdminMODE AdminMODE = new AdminMODE();
            AdminMODE.setVisible(true);;
        }
    }//GEN-LAST:event_jButtonBotonIngresarComoAdminUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINMODE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINMODE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBotonIngresarComoAdminUsuario;
    private javax.swing.JLabel jLabelComoDeseaIngresar;
    private javax.swing.JLabel jLabelEscribeModo;
    private javax.swing.JTextField jTextFieldColocaELModo;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
