/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAdivinanza;

/**
 *
 * @author ROY2404
 */
public class ModificarPreguntasRespuestas extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPreguntasRespuestas
     */
    public ModificarPreguntasRespuestas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelModificarPregunta = new javax.swing.JLabel();
        jLabelIngreseIndiceDePreguntaParaModificar = new javax.swing.JLabel();
        jTextFieldColocarIndiceDePregunta = new javax.swing.JTextField();
        jLabelIngreseNuevaPregunta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneColocarNuevaPregunta = new javax.swing.JTextPane();
        jLabelIngreseNuevaRespuesta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneColocarNuevaRespuesta = new javax.swing.JTextPane();
        jButtonGuardarCambiosDeModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelModificarPregunta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelModificarPregunta.setText("MODIFICAR  PREGUNTA Y RESPUESTA");

        jLabelIngreseIndiceDePreguntaParaModificar.setText("Ingrese el índice de la pregunta que desea modificar:");

        jTextFieldColocarIndiceDePregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColocarIndiceDePreguntaActionPerformed(evt);
            }
        });

        jLabelIngreseNuevaPregunta.setText("Ingrese la nueva pregunta:");

        jScrollPane1.setViewportView(jTextPaneColocarNuevaPregunta);

        jLabelIngreseNuevaRespuesta.setText("Ingrese la nueva respuesta:");

        jScrollPane2.setViewportView(jTextPaneColocarNuevaRespuesta);

        jButtonGuardarCambiosDeModificar.setText("Guardar Cambios");
        jButtonGuardarCambiosDeModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarCambiosDeModificarMouseClicked(evt);
            }
        });
        jButtonGuardarCambiosDeModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosDeModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIngreseNuevaPregunta)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIngreseIndiceDePreguntaParaModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldColocarIndiceDePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIngreseNuevaRespuesta)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabelModificarPregunta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jButtonGuardarCambiosDeModificar)))
                        .addGap(0, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelModificarPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIngreseIndiceDePreguntaParaModificar)
                    .addComponent(jTextFieldColocarIndiceDePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelIngreseNuevaPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabelIngreseNuevaRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGuardarCambiosDeModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldColocarIndiceDePreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColocarIndiceDePreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColocarIndiceDePreguntaActionPerformed

    private void jButtonGuardarCambiosDeModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosDeModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarCambiosDeModificarActionPerformed

    private void jButtonGuardarCambiosDeModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosDeModificarMouseClicked
        AdminMODE ventanaAdminMODE = new AdminMODE();
        ventanaAdminMODE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGuardarCambiosDeModificarMouseClicked

    /**
     * @param argsjLabelModificarPreguntammand line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPreguntasRespuestas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarCambiosDeModificar;
    private javax.swing.JLabel jLabelIngreseIndiceDePreguntaParaModificar;
    private javax.swing.JLabel jLabelIngreseNuevaPregunta;
    private javax.swing.JLabel jLabelIngreseNuevaRespuesta;
    private javax.swing.JLabel jLabelModificarPregunta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldColocarIndiceDePregunta;
    private javax.swing.JTextPane jTextPaneColocarNuevaPregunta;
    private javax.swing.JTextPane jTextPaneColocarNuevaRespuesta;
    // End of variables declaration//GEN-END:variables
}
